### ISSUE TITLE
Players with jump boost don't take fall damage

### ISSUE THREAD

**Issue by Wruczek** [Updated-NoCheatPlus/NoCheatPlus#108]
### Full output of /ncp version

```
---- Version information ----
#### Server ####
git-PaperSpigot-"4c7641d" ~MC: 1.8.8~
  detected: 1.8.8
#### NoCheatPlus ####
Plugin: 3.17-SNAPSHOT-Updated-b93
MCAccess: 1.8.4-1.8.8 / Spigot-CB-1.8_R3
Features:
  blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8
  checks: FastConsume | Gutenberg | AttackFrequency | FlyingFrequency | KeepAliveFrequency
  defaults: pvpKnockBackVelocity
  packet-listeners: UseEntityAdapter | MovingFlying | OutgoingPosition | KeepAliveAdapter | SoundDistance | WrongTurnAdapter | CatchAllAdapter | NoSlow | Fight
Hooks: AllViolations~NCP~ 1.0 | ViolationFrequency~NCP~ 1.0
#### Related Plugins ####
ProtocolLib v4.4.0-SNAPSHOT-b403
```

### Describe the issue
After changing `survivalfly.active` to `false` players with jump boost effect no longer take fall damage (Minecraft 1.8).
Without the potion players take damage as expected.

### How to reproduce the issue
1. Change `survivalfly.active` to `false`
2. Get yourself a jump boost potion
3. Fall from height
4. You will not take any damage

### Any possible config options changed or plugins that may cause interference?
Confirmed on default configuration with only NCP installed.
