### ISSUE TITLE
Path blocks falsely flagging survivalfly

### ISSUE THREAD

**Issue by p9sq** [Updated-NoCheatPlus/NoCheatPlus#206]
### Full output of /ncp version
```
---- Version information ----
#### NoCheatPlus ####
Plugin: 3.16.0-RC-sMD5NET-b1134
MCAccess: 1.4.6-1.11.2I? / Bukkit-API
Features:
   blocks: BlocksMC1_4 | BlocksMC1_5 | BlocksMC1_6_1 | BlocksMC1_7_2 | BlocksMC1_8 | BlocksMC1_9 | BlocksMC1_10 | BlocksMC1_11 | BlocksMC1_12
   checks: FastConsume | Gutenberg | HotFixFallingBlockPortalEnter
   defaults: pvpKnockBackVelocity
Hooks: AllViolations~NCP~ 1.0
```

### Describe the issue
Flight is false flagging when standing on path blocks

### How to reproduce the issue
This issue is always happening to me and I've got no idea how to fix it. Well, the only way to get unstuck from NCP falsely flagging is to break the path block you are standing on.

### Extra links: video and/or debug log (instructions: https://github.com/Updated-NoCheatPlus/Docs/blob/master/Development/Debugging.md#on-the-fly-debug-output-for-individual-players)
Do I have to add videos? The only thing that happens when standing on path blocks is that ncp just lags the player back and I get alerts saying "{player} failed moving.survivalfly"

### Any possible config options changed or plugins that may cause interference?
My server is a multi-version anarchy server. I've configured NCP so then all checks are disabled, excluding noswing and survivalfly.
